version: 1.0-{build}
build: off
branches:
  only:
    - master
    - cython
    - appveyor
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python2"
      STACK: "2.7"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.5"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.6"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.7"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      STACK: "2.7"
      BASSLIB: "bass24"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      STACK: "2.7"
      BASSLIB: "bass24\\x64"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      STACK: "3.7"
      BASSLIB: "bass24"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      STACK: "3.7"
      BASSLIB: "bass24\\x64"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      STACK: "3.6"
      BASSLIB: "bass24"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      STACK: "3.6"
      BASSLIB: "bass24\\x64"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      STACK: "3.5"
      BASSLIB: "bass24"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      STACK: "3.5"
      BASSLIB: "bass24\\x64"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      STACK: "2.7"
      BASSLIB: "bass24"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
      SDIST_ONLY: 1

stack: python %STACK%

before_build:
  - ps: |
      $wc = New-Object System.Net.WebClient
      $wc.DownloadFile("http://www.un4seen.com/files/bass24.zip", "$($env:BUILD_FOLDER)bass24.zip")
  - cmd: 7z x bass24.zip -o%BUILD_FOLDER%bass24 -r
  - sh: |
      wget http://www.un4seen.com/files/bass24-linux.zip
      7z x bass24-linux.zip -o${BUILD_FOLDER}bass24-linux -r
      
install:
  - cmd: |
      %PYTHON%\python.exe --version
      %PYTHON%\Scripts\pip.exe --version
      %PYTHON%\python.exe -m pip install -r requirements-dev.txt
  - sh: |
      $PYTHON --version
      $PYTHON -m pip --version
      $PYTHON -m pip install -r requirements-dev.txt
build_script:
  - cmd: "
      IF %SDIST_ONLY% == 1 (
        %PYTHON%\\python.exe setup.py sdist
      ) ELSE (
        %PYTHON%\\python.exe setup.py build_ext --inplace
        %PYTHON%\\python.exe setup.py bdist_wheel
      )"
  - sh: |
      if [ -z ${SDIST_ONLY+x} ];
      then
        $PYTHON setup.py build_ext --inplace
        $PYTHON setup.py bdist_wheel
      else
        $PYTHON setup.py sdist
      fi

before_test:
  - sh: |
      export LD_LIBRARY_PATH=${BUILD_FOLDER}bass24-linux/x64/
  - cmd: |
      set PATH=%BUILD_FOLDER%%BASSLIB%;%PATH%

test_script:
  - sh: |
      if [ -z ${SDIST_ONLY+x} ];
      then
        nose2 -X
      fi
  - cmd: |
      if not defined SDIST_ONLY %PYTHON%\Scripts\nose2.exe -X

on_finish:
  - ps: |
      if (Test-Path "$($env:BUILD_FOLDER)nose2-junit.xml")
      {
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "$($env:BUILD_FOLDER)nose2-junit.xml")
      }
  - sh: |
      if [ -f "${BUILD_FOLDER}nose2-junit.xml" ];
      then
        curl -F "file=@${BUILD_FOLDER}nose2-junit.xml" "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"
      fi

init:
  - cmd: |
      ECHO Python %PYTHON_VERSION% (%PYTHON_ARCH%bit) from %PYTHON%
artifacts:
  - path: dist/*
