build: off
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python2"
      STACK: "2.7"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.5"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.6"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.7"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.8"
      BUILD_FOLDER: "/home/appveyor/projects/bass4py/"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      STACK: "2.7"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      STACK: "2.7"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      STACK: "3.8"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      STACK: "3.8"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      STACK: "3.7"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      STACK: "3.7"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      STACK: "3.6"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      STACK: "3.6"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      STACK: "3.5"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      STACK: "3.5"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      STACK: "2.7"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
      BUILD_FOLDER: "C:\\projects\\bass4py\\"
      SDIST_ONLY: 1

stack: python %STACK%

before_build:
  - ps: |
      if($isWindows)
      {
        $wc = New-Object System.Net.WebClient
        $wc.DownloadFile("http://www.un4seen.com/files/bass24.zip", "$($env:BUILD_FOLDER)bass24.zip")
        $wc.DownloadFile("http://www.un4seen.com/files/z/3/tags18.zip", "$($env:BUILD_FOLDER)tags18.zip")
        & 7z --% x -bb3 bass24.zip -o$($env:BUILD_FOLDER)bass24 -r
        & 7z --% x -bb3 tags18.zip -o$($env:BUILD_FOLDER)tags18 -r
      } else {
        & wget http://www.un4seen.com/files/bass24-linux.zip
        & wget http://www.un4seen.com/files/z/3/tags18-linux.zip
        & 7z --% x -bb3 bass24-linux.zip -o$($env:BUILD_FOLDER)bass24-linux -r
        & 7z --% x -bb3 tags18-linux.zip -o$($env:BUILD_FOLDER)tags18-linux -r
      }
      
install:
  - ps: |
      if($isWindows)
      {
        $version = &"$($env:PYTHON)\python.exe" -c --% "from Bass4Py import __version__; import sys; _ = sys.stdout.write(__version__)"
      } else {
        $version = & $($env:PYTHON) -c --% "from Bass4Py import __version__; import sys; _ = sys.stdout.write(__version__)"
      }
      Update-AppveyorBuild -Version "$($version)+$($env:APPVEYOR_BUILD_NUMBER)"
  - cmd: |
      %PYTHON%\python.exe --version
      %PYTHON%\Scripts\pip.exe --version
      %PYTHON%\python.exe -m pip install -r requirements-dev.txt
  - sh: |
      $PYTHON --version
      $PYTHON -m pip --version
      $PYTHON -m pip install -r requirements-dev.txt
build_script:
  - cmd: "
      IF [%SDIST_ONLY%]==[1] (
        %PYTHON%\\python.exe setup.py sdist
      ) ELSE (
        %PYTHON%\\python.exe setup.py build_ext --inplace &&
        %PYTHON%\\python.exe setup.py bdist_wheel
      )"
  - sh: |
      if [ -z ${SDIST_ONLY+x} ];
      then
        $PYTHON setup.py build_ext --inplace
        $PYTHON setup.py bdist_wheel
      else
        $PYTHON setup.py sdist
      fi

before_test:
  - sh: |
      export LD_LIBRARY_PATH=${BUILD_FOLDER}bass24-linux/x64/:${BUILD_FOLDER}tags18-linux/x64/
  - cmd: |
      set PATH=%BUILD_FOLDER%%BASSLIB%;%BUILD_FOLDER%%TAGSLIB%;%PATH%

test_script:
  - sh: |
      if [ -z ${SDIST_ONLY+x} ];
      then
        nose2 -X
      fi
  - cmd: |
      if not defined SDIST_ONLY %PYTHON%\Scripts\nose2.exe -X

on_finish:
  - ps: |
      if (Test-Path "$($env:BUILD_FOLDER)nose2-junit.xml")
      {
        if($isWindows)
        {
          $wc = New-Object 'System.Net.WebClient'
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "$($env:BUILD_FOLDER)nose2-junit.xml")
        } else {
          & curl --% -F "file=@$($env:BUILD_FOLDER)nose2-junit.xml" "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
        }
      }

artifacts:
  - path: dist/*
